name: CD
on:
  push:
    branches:
      - master
env:
  NETCORE_VERSION: '5.0.100'

jobs:
  release:
    runs-on: ubuntu-latest
    name: CD
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
      - name: Build docker image
        run: docker build -t categorise .
      - name: Push to image to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:push -a ${{ secrets.APP_NAME }} web
      - name: Release image
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release -a ${{ secrets.APP_NAME }} web
      - name: Logout of Heroku
        run: heroku container:logout